.include "macro.inc"

.section .sbss

.align 4

/* Generated by spimdisasm 1.26.1 */

dlabel _fbss, global
/* 29AA00 00399A00 */ .space 0x08

dlabel MSGCOL, local
/* 29AA08 00399A08 */ .space 0x01

dlabel B_00399A09
/* 29AA09 00399A09 */ .space 0x01

dlabel B_00399A0A
/* 29AA0A 00399A0A */ .space 0x06

dlabel MSGSIZE, local
/* 29AA10 00399A10 */ .space 0x02

dlabel B_00399A12
/* 29AA12 00399A12 */ .space 0x02

dlabel MSGZPOP, local
/* 29AA14 00399A14 */ .space 0x04

dlabel th_id_Ctrl, local
/* 29AA18 00399A18 */ .space 0x04

dlabel cmngif_pri_cnt, local
/* 29AA1C 00399A1C */ .space 0x04

dlabel cmnGifPkBase, local
/* 29AA20 00399A20 */ .space 0x04

dlabel cmnGifPkCurrent, local
/* 29AA24 00399A24 */ .space 0x04

dlabel cmnGifPkEnd, local
/* 29AA28 00399A28 */ .space 0x04

dlabel usrMemPosCnt, local
/* 29AA2C 00399A2C */ .space 0x04

dlabel usrMemPosEndCnt, local
/* 29AA30 00399A30 */ .space 0x04

dlabel cdSampleTmp, local
/* 29AA34 00399A34 */ .space 0x04

dlabel follow_scr_tap_memory_cnt, local
/* 29AA38 00399A38 */ .space 0x04

dlabel follow_scr_tap_memory_cnt_load, local
/* 29AA3C 00399A3C */ .space 0x04

dlabel commake_str_cnt, local
/* 29AA40 00399A40 */ .space 0x04

dlabel sprDmaC, local
/* 29AA44 00399A44 */ .space 0x04

dlabel kanji_pp, local
/* 29AA48 00399A48 */ .space 0x04

dlabel dr_tap_req_num, local
/* 29AA4C 00399A4C */ .space 0x04

dlabel scenectrl_outside_cnt, local
/* 29AA50 00399A50 */ .space 0x04

dlabel scenectrl_outside_read_cnt, local
/* 29AA54 00399A54 */ .space 0x04

dlabel mozaiku_poll_str_current_pp, local
/* 29AA58 00399A58 */ .space 0x04

dlabel drawCurrentLine, local
/* 29AA5C 00399A5C */ .space 0x04

dlabel drawCurrentTime, local
/* 29AA60 00399A60 */ .space 0x04

dlabel drawCurrentTimeOld, local
/* 29AA64 00399A64 */ .space 0x04

dlabel drawEventrec, local
/* 29AA68 00399A68 */ .space 0x04

dlabel useDispFlag, local
/* 29AA6C 00399A6C */ .space 0x04

dlabel drDispFlag, local
/* 29AA70 00399A70 */ .space 0x04

dlabel men_ctrl_ratio, local
/* 29AA74 00399A74 */ .space 0x04

dlabel men_ctrl_enum, local
/* 29AA78 00399A78 */ .space 0x04

dlabel ddbg_pause_f, local
/* 29AA7C 00399A7C */ .space 0x04

dlabel exam_global_ply_current, local
/* 29AA80 00399A80 */ .space 0x04

dlabel mbar_ctrl_time, local
/* 29AA84 00399A84 */ .space 0x04

dlabel mbar_ctrl_stage, local
/* 29AA88 00399A88 */ .space 0x04

dlabel mbar_ctrl_stage_selT, local
/* 29AA8C 00399A8C */ .space 0x04

dlabel guime_hdl, local
/* 29AA90 00399A90 */ .space 0x04

dlabel guime_camera_hdl, local
/* 29AA94 00399A94 */ .space 0x04

dlabel ldmap_hdl, local
/* 29AA98 00399A98 */ .space 0x08

dlabel mc_holdTmp, local
/* 29AAA0 00399AA0 */ .space 0x08

dlabel mc_resetTmp, local
/* 29AAA8 00399AA8 */ .space 0x04

dlabel p3str_pp, local
/* 29AAAC 00399AAC */ .space 0x04

dlabel adrd_common, local
/* 29AAB0 00399AB0 */ .space 0x04

dlabel adrd_common_cnt, local
/* 29AAB4 00399AB4 */ .space 0x04

dlabel p3str_sort_cnt, local
/* 29AAB8 00399AB8 */ .space 0x04

dlabel bFirst, local
/* 29AABC 00399ABC */ .space 0x04

dlabel VsLev, local
/* 29AAC0 00399AC0 */ .space 0x04

dlabel AMusicFitTime, local
/* 29AAC4 00399AC4 */ .space 0x04

dlabel state.248, local
/* 29AAC8 00399AC8 */ .space 0x04

dlabel mesNo.249, local
/* 29AACC 00399ACC */ .space 0x04

dlabel state.253, local
/* 29AAD0 00399AD0 */ .space 0x04

dlabel state.264, local
/* 29AAD4 00399AD4 */ .space 0x04

dlabel saveSel.265, local
/* 29AAD8 00399AD8 */ .space 0x04

dlabel waitTime.266, local
/* 29AADC 00399ADC */ .space 0x04

dlabel state.270, local
/* 29AAE0 00399AE0 */ .space 0x04

dlabel waitTime.271, local
/* 29AAE4 00399AE4 */ .space 0x04

dlabel scstate.273, local
/* 29AAE8 00399AE8 */ .space 0x04

dlabel scstPos.274, local
/* 29AAEC 00399AEC */ .space 0x04

dlabel curTag.275, local
/* 29AAF0 00399AF0 */ .space 0x04

dlabel fphs_pos.276, local
/* 29AAF4 00399AF4 */ .space 0x04

dlabel AnmBit.277, local
/* 29AAF8 00399AF8 */ .space 0x04

dlabel state.296, local
/* 29AAFC 00399AFC */ .space 0x04

dlabel scstate.433, local
/* 29AB00 00399B00 */ .space 0x04

dlabel scstPos.434, local
/* 29AB04 00399B04 */ .space 0x04

dlabel opt_lang.459, local
/* 29AB08 00399B08 */ .space 0x04

dlabel opt_subt.460, local
/* 29AB0C 00399B0C */ .space 0x04

dlabel opt_vibr.461, local
/* 29AB10 00399B10 */ .space 0x04

dlabel opt_oneb.462, local
/* 29AB14 00399B14 */ .space 0x04

dlabel pP3GameState, local
/* 29AB18 00399B18 */ .space 0x04

dlabel _bMapCaptureReq, local
/* 29AB1C 00399B1C */ .space 0x04

dlabel _MNwaitTime, local
/* 29AB20 00399B20 */ .space 0x04

dlabel CurMapOldFlg, local
/* 29AB24 00399B24 */ .space 0x04

dlabel CurMapNo, local
/* 29AB28 00399B28 */ .space 0x04

dlabel CurMapBakFlg, local
/* 29AB2C 00399B2C */ .space 0x04

dlabel CurMapState, local
/* 29AB30 00399B30 */ .space 0x04

dlabel UserWork, local
/* 29AB34 00399B34 */ .space 0x04

dlabel pCStageRank, local
/* 29AB38 00399B38 */ .space 0x04

dlabel UserLst, local
/* 29AB3C 00399B3C */ .space 0x04

dlabel UserDispWork, local
/* 29AB40 00399B40 */ .space 0x04

dlabel UCheckLoadError, local
/* 29AB44 00399B44 */ .space 0x04

dlabel UCheckSaveError, local
/* 29AB48 00399B48 */ .space 0x04

dlabel subStatus, local
/* 29AB4C 00399B4C */ .space 0x04

dlabel ret, local
/* 29AB50 00399B50 */ .space 0x04

dlabel errorNo, local
/* 29AB54 00399B54 */ .space 0x04

dlabel waitTime, local
/* 29AB58 00399B58 */ .space 0x04

dlabel pGameData, local
/* 29AB5C 00399B5C */ .space 0x04

dlabel FreeSizeFlg, local
/* 29AB60 00399B60 */ .space 0x04

dlabel portCheckFlg, local
/* 29AB64 00399B64 */ .space 0x04

dlabel NeedSize, local
/* 29AB68 00399B68 */ .space 0x04

dlabel B_00399B6C
/* 29AB6C 00399B6C */ .space 0x04

dlabel UChkSize, local
/* 29AB70 00399B70 */ .space 0x04

dlabel B_00399B74
/* 29AB74 00399B74 */ .space 0x04

dlabel isFileFlgCash, local
/* 29AB78 00399B78 */ .space 0x04

dlabel _AnimeFontFlg, local
/* 29AB7C 00399B7C */ .space 0x04

dlabel kanji_pp, local
/* 29AB80 00399B80 */ .space 0x04

dlabel _PkScrW, local
/* 29AB84 00399B84 */ .space 0x04

dlabel _PkScrH, local
/* 29AB88 00399B88 */ .space 0x04

dlabel workAreaSize, local
/* 29AB8C 00399B8C */ .space 0x04

dlabel debugParam, local
/* 29AB90 00399B90 */ .space 0x04

dlabel AwfulStatus, local
/* 29AB94 00399B94 */ .space 0x04

dlabel MendererCreateTextureEntryPoint, local
/* 29AB98 00399B98 */ .space 0x04

dlabel MendererDrawMeshEntryPoint, local
/* 29AB9C 00399B9C */ .space 0x04

dlabel return_buffer.1822, local
/* 29ABA0 00399BA0 */ .space 0x04

dlabel return_buffer.1826, local
/* 29ABA4 00399BA4 */ .space 0x04

dlabel noodleStatus, local
/* 29ABA8 00399BA8 */ .space 0x04

dlabel noodleChangeTimer, local
/* 29ABAC 00399BAC */ .space 0x04

dlabel noodleDeltaRotation, local
/* 29ABB0 00399BB0 */ .space 0x04

dlabel mendererBackgroundPicture, local
/* 29ABB4 00399BB4 */ .space 0x04

dlabel mendererAwfulColor, local
/* 29ABB8 00399BB8 */ .space 0x04

dlabel awfulStatus, local
/* 29ABBC 00399BBC */ .space 0x04

dlabel awfulChangeTimer, local
/* 29ABC0 00399BC0 */ .space 0x04

dlabel awfulRotation, local
/* 29ABC4 00399BC4 */ .space 0x04

dlabel WV_SCREEN_W, local
/* 29ABC8 00399BC8 */ .space 0x04

dlabel WV_SCREEN_H, local
/* 29ABCC 00399BCC */ .space 0x04

dlabel __ti9exception, global
/* 29ABD0 00399BD0 */ .space 0x08

dlabel __ti9type_info, global
/* 29ABD8 00399BD8 */ .space 0x08

dlabel errno, global
/* 29ABE0 00399BE0 */ .space 0x04
