.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64     # allow use of 64-bit general purpose registers

.section .bss

.align 4

/* Generated by spimdisasm 1.18.0 */

dlabel _args
/* 29AA1C 00399C00 */ .space 0x148

dlabel ob.3
/* 29AB64 00399D48 */ .space 0x18

dlabel dbgPacket
/* 29AB7C 00399D60 */ .space 0x10000

dlabel gifPacket
/* 2AAB7C 003A9D60 */ .space 0x10

dlabel tinfo
/* 2AAB8C 003A9D70 */ .space 0x20

dlabel mtcStack_CTRL
/* 2AABAC 003A9D90 */ .space 0x1000

dlabel mtcStack_MAIN
/* 2ABBAC 003AAD90 */ .space 0x1000

dlabel mtcStack_02
/* 2ACBAC 003ABD90 */ .space 0x100

dlabel mtcStack_03
/* 2ACCAC 003ABE90 */ .space 0x800

dlabel mtcStack_04
/* 2AD4AC 003AC690 */ .space 0x1000

dlabel mtcStack_05
/* 2AE4AC 003AD690 */ .space 0x4000

dlabel mtcStack_06
/* 2B24AC 003B1690 */ .space 0x100

dlabel mtcStack_07
/* 2B25AC 003B1790 */ .space 0x4000

dlabel mtcStack_08
/* 2B65AC 003B5790 */ .space 0x100

dlabel mtcStack_09
/* 2B66AC 003B5890 */ .space 0x100

dlabel mtcStack_0A
/* 2B67AC 003B5990 */ .space 0x1000

dlabel mtcStack_0B
/* 2B77AC 003B6990 */ .space 0x100

dlabel mtcStack_0C
/* 2B78AC 003B6A90 */ .space 0x100

dlabel mtcStack_0D
/* 2B79AC 003B6B90 */ .space 0x1000

dlabel mtcStack_0E
/* 2B89AC 003B7B90 */ .space 0x100

dlabel mtcStack_0F
/* 2B8AAC 003B7C90 */ .space 0x1000

dlabel mtcTaskConB
/* 2B9AAC 003B8C90 */ .space 0x400

dlabel mtcStack_Ctrl
/* 2B9EAC 003B9090 */ .space 0x1000

dlabel th_para_Ctrl
/* 2BAEAC 003BA090 */ .space 0x30

dlabel s.153
/* 2BAEDC 003BA0C0 */ .space 0x40

dlabel pad_dma_buf
/* 2BAF1C 003BA100 */ .space 0x200

dlabel ChangeDrawAreaPacket
/* 2BB11C 003BA300 */ .space 0xC0

dlabel exl_dmatag
/* 2BB1DC 003BA3C0 */ .space 0x10

dlabel usr_malloc_str
/* 2BB1EC 003BA3D0 */ .space 0x800

dlabel GifPkCommon
/* 2BB9EC 003BABD0 */ .space 0x20000

dlabel drawEnvSp
/* 2DB9EC 003DABD0 */ .space 0x80

dlabel drawEnvZbuff
/* 2DBA6C 003DAC50 */ .space 0x80

dlabel drawEnvEnd
/* 2DBAEC 003DACD0 */ .space 0x80

dlabel cmngif_pri
/* 2DBB6C 003DAD50 */ .space 0x200

dlabel cmnGifTr
/* 2DBD6C 003DAF50 */ .space 0x410

dlabel cmnGifPacket
/* 2DC17C 003DB360 */ .space 0x20

dlabel usrMemoryData
/* 2DC19C 003DB380 */ .space 0x1880000

dlabel usrMemPos
/* 1B5C19C 01C5B380 */ .space 0x1ADB

dlabel B_1C5CE5B
/* 1B5DC77 01C5CE5B */ .space 0x521

dlabel B_1C5D37C
/* 1B5E198 01C5D37C */ .space 0x04

dlabel tp.87
/* 1B5E19C 01C5D380 */ .space 0x60

dlabel tp.94
/* 1B5E1FC 01C5D3E0 */ .space 0x60

dlabel tp.98
/* 1B5E25C 01C5D440 */ .space 0x60

dlabel tp.111
/* 1B5E2BC 01C5D4A0 */ .space 0x60

dlabel tp.115
/* 1B5E31C 01C5D500 */ .space 0xB00

dlabel RBuff
/* 1B5EE1C 01C5E000 */ .space 0x1011

# Automatically generated and unreferenced pad
dlabel B_1C5F011
/* 1B5FE2D 01C5F011 */ .space 0x07

dlabel cdctrl_str
/* 1B5FE34 01C5F018 */ .space 0x10

dlabel B_1C5F028
/* 1B5FE44 01C5F028 */ .space 0x06

dlabel B_1C5F02E
/* 1B5FE4A 01C5F02E */ .space 0x02

dlabel scr_sndtap_pp
/* 1B5FE4C 01C5F030 */ .space 0x10

dlabel score_indv_str
/* 1B5FE5C 01C5F040 */ .space 0x4A24

# Automatically generated and unreferenced pad
dlabel B_1C63A64
/* 1B64880 01C63A64 */ .space 0x04

dlabel follow_scr_tap_memory
/* 1B64884 01C63A68 */ .space 0xC00

dlabel tap_groupe_str
/* 1B65484 01C64668 */ .space 0x50

dlabel commake_str
/* 1B654D4 01C646B8 */ .space 0x100

dlabel exam_check
/* 1B655D4 01C647B8 */ .space 0x668

dlabel B_1C64E20
/* 1B65C3C 01C64E20 */ .space 0xCE0

dlabel yaku_tmp_buf
/* 1B6691C 01C65B00 */ .space 0x28

dlabel bng_str
/* 1B66944 01C65B28 */ .space 0x18

dlabel B_1C65B40
/* 1B6695C 01C65B40 */ .space 0x40

dlabel sprPacket
/* 1B6699C 01C65B80 */ .space 0x8000

dlabel gifPkSpr
/* 1B6E99C 01C6DB80 */ .space 0x10

dlabel fmode_ctrl_str
/* 1B6E9AC 01C6DB90 */ .space 0x10

dlabel subtPkSpr
/* 1B6E9BC 01C6DBA0 */ .space 0x10

dlabel subt_code
/* 1B6E9CC 01C6DBB0 */ .space 0x80

dlabel mcode_dat_pp
/* 1B6EA4C 01C6DC30 */ .space 0x400

dlabel dr_tap_req
/* 1B6EE4C 01C6E030 */ .space 0xC0

dlabel octst_time
/* 1B6EF0C 01C6E0F0 */ .space 0x20

dlabel octst_timeLoad
/* 1B6EF2C 01C6E110 */ .space 0x20

dlabel scenectrl_outside
/* 1B6EF4C 01C6E130 */ .space 0x100

dlabel bthrow_ctrl
/* 1B6F04C 01C6E230 */ .space 0x04

dlabel B_1C6E234
/* 1B6F050 01C6E234 */ .space 0xE04

dlabel B_1C6F038
/* 1B6FE54 01C6F038 */ .space 0xE20

dlabel tmp_buf_adrs
/* 1B70C74 01C6FE58 */ .space 0x40

dlabel check_scenectrl
/* 1B70CB4 01C6FE98 */ .space 0x58

dlabel gs_simage
/* 1B70D0C 01C6FEF0 */ .space 0x70

dlabel gs_loadimg
/* 1B70D7C 01C6FF60 */ .space 0x60

dlabel tp.72
/* 1B70DDC 01C6FFC0 */ .space 0x60

dlabel mbarNiko_gif.301
/* 1B70E3C 01C70020 */ .space 0x10

dlabel exam_global_ply
/* 1B70E4C 01C70030 */ .space 0x10

dlabel exam_global_ply_current_ply
/* 1B70E5C 01C70040 */ .space 0x10

dlabel metFrameCnt
/* 1B70E6C 01C70050 */ .space 0x04

dlabel B_1C70054
/* 1B70E70 01C70054 */ .space 0x04

dlabel B_1C70058
/* 1B70E74 01C70058 */ .space 0x08

dlabel metFrameCntLight
/* 1B70E7C 01C70060 */ .space 0x04

dlabel B_1C70064
/* 1B70E80 01C70064 */ .space 0x04

dlabel B_1C70068
/* 1B70E84 01C70068 */ .space 0x08

dlabel scr_tenmetu_col_dat
/* 1B70E8C 01C70070 */ .space 0x10

dlabel conditionFramCnt
/* 1B70E9C 01C70080 */ .space 0x10

dlabel vsScoreMove
/* 1B70EAC 01C70090 */ .space 0x04

dlabel B_1C70094
/* 1B70EB0 01C70094 */ .space 0x0C

dlabel vsScoreAni
/* 1B70EBC 01C700A0 */ .space 0x04

dlabel B_1C700A4
/* 1B70EC0 01C700A4 */ .space 0x0C

dlabel vs_scr_ctrl
/* 1B70ECC 01C700B0 */ .space 0x60

dlabel mbar_req_str
/* 1B70F2C 01C70110 */ .space 0x04

dlabel B_1C70114
/* 1B70F30 01C70114 */ .space 0x40

dlabel B_1C70154
/* 1B70F70 01C70154 */ .space 0x74

dlabel mbar_gif
/* 1B70FE4 01C701C8 */ .space 0x1E38

dlabel RBuff
/* 1B72E1C 01C72000 */ .space 0x1011

# Automatically generated and unreferenced pad
dlabel B_1C73011
/* 1B73E2D 01C73011 */ .space 0x07

dlabel vsync_time
/* 1B73E34 01C73018 */ .space 0xD0

dlabel mc_rep_str_local
/* 1B73F04 01C730E8 */ .space 0x10A4

dlabel B_1C7418C
/* 1B74FA8 01C7418C */ .space 0x3484

dlabel mc_rep_ctrl
/* 1B7842C 01C77610 */ .space 0x08

dlabel B_1C77618
/* 1B78434 01C77618 */ .space 0x18

dlabel menu_str
/* 1B7844C 01C77630 */ .space 0x08

dlabel B_1C77638
/* 1B78454 01C77638 */ .space 0x08

dlabel p3str_sort
/* 1B7845C 01C77640 */ .space 0xC0

dlabel cm_str_ctrl
/* 1B7851C 01C77700 */ .space 0x1C8

dlabel P3Log_Val
/* 1B786E4 01C778C8 */ .space 0x188

dlabel MapCity.254
/* 1B7886C 01C77A50 */ .space 0x04

dlabel B_1C77A54
/* 1B78870 01C77A54 */ .space 0x34

dlabel MapCHall.272
/* 1B788A4 01C77A88 */ .space 0x38

dlabel menuPadState
/* 1B788DC 01C77AC0 */ .space 0x20

dlabel TsSndChan
/* 1B788FC 01C77AE0 */ .space 0x130

dlabel TsBGMState
/* 1B78A2C 01C77C10 */ .space 0x1C

dlabel B_1C77C2C
/* 1B78A48 01C77C2C */ .space 0x84

dlabel MNS_StageMap2
/* 1B78ACC 01C77CB0 */ .space 0x1158

dlabel MNS_CityHall
/* 1B79C24 01C78E08 */ .space 0x1158

dlabel MNS_OptCounter
/* 1B7AD7C 01C79F60 */ .space 0x1158

dlabel MNS_RepCounter
/* 1B7BED4 01C7B0B8 */ .space 0x1158

dlabel MNS_StgCounter
/* 1B7D02C 01C7C210 */ .space 0x1154

dlabel B_1C7D364
/* 1B7E180 01C7D364 */ .space 0x1154

dlabel MNS_JimakuBak
/* 1B7F2D4 01C7E4B8 */ .space 0x1158

dlabel CurRankScore
/* 1B8042C 01C7F610 */ .space 0x18

dlabel CurFileInfo
/* 1B80444 01C7F628 */ .space 0x04

dlabel B_1C7F62C
/* 1B80448 01C7F62C */ .space 0x0C

dlabel B_1C7F638
/* 1B80454 01C7F638 */ .space 0x08

dlabel MnPkt
/* 1B8045C 01C7F640 */ .space 0xA0

dlabel MnLPkt
/* 1B804FC 01C7F6E0 */ .space 0xA0

dlabel FPacket
/* 1B8059C 01C7F780 */ .space 0x10

dlabel MCMesWork
/* 1B805AC 01C7F790 */ .space 0x08

dlabel B_1C7F798
/* 1B805B4 01C7F798 */ .space 0x30

dlabel CmpMesWork
/* 1B805E4 01C7F7C8 */ .space 0x18

dlabel RankLst
/* 1B805FC 01C7F7E0 */ .space 0x190

dlabel PopupMenu
/* 1B8078C 01C7F970 */ .space 0x118

dlabel SaveMenu
/* 1B808A4 01C7FA88 */ .space 0xC0

dlabel JukeMenu
/* 1B80964 01C7FB48 */ .space 0x4B9

dlabel B_1C80001
/* 1B80E1D 01C80001 */ .space 0xCAF

dlabel B_1C80CB0
/* 1B81ACC 01C80CB0 */ .space 0x2B0

dlabel OptionMenu
/* 1B81D7C 01C80F60 */ .space 0x0C

dlabel B_1C80F6C
/* 1B81D88 01C80F6C */ .space 0x30

dlabel B_1C80F9C
/* 1B81DB8 01C80F9C */ .space 0x14

dlabel UserListMenu
/* 1B81DCC 01C80FB0 */ .space 0x1C

dlabel B_1C80FCC
/* 1B81DE8 01C80FCC */ .space 0xFC

dlabel ScFade
/* 1B81EE4 01C810C8 */ .space 0x38

dlabel P3MC_Work
/* 1B81F1C 01C81100 */ .space 0x20

dlabel filePath
/* 1B81F3C 01C81120 */ .space 0x40

dlabel mcmenu_info
/* 1B81F7C 01C81160 */ .space 0x04

dlabel B_1C81164
/* 1B81F80 01C81164 */ .space 0x10

dlabel B_1C81174
/* 1B81F90 01C81174 */ .space 0x0C

dlabel p3mcTblGetDir
/* 1B81F9C 01C81180 */ .space 0x200

dlabel McLogFileFlg
/* 1B8219C 01C81380 */ .space 0x50

dlabel McReplayFileFlg
/* 1B821EC 01C813D0 */ .space 0x70

dlabel tmps.18
/* 1B8225C 01C81440 */ .space 0x40

dlabel tmps.22
/* 1B8229C 01C81480 */ .space 0xC0

dlabel memc_stat
/* 1B8235C 01C81540 */ .space 0x28

dlabel B_1C81568
/* 1B82384 01C81568 */ .space 0x0C

dlabel B_1C81574
/* 1B82390 01C81574 */ .space 0x28C

dlabel B_1C81800
/* 1B8261C 01C81800 */ .space 0x80

dlabel mcode_dat_pp
/* 1B8269C 01C81880 */ .space 0x1000

dlabel MnSubtFontInfo
/* 1B8369C 01C82880 */ .space 0x40

dlabel sbuff
/* 1B836DC 01C828C0 */ .space 0x100

dlabel gCd
/* 1B837DC 01C829C0 */ .space 0x40

dlabel sbuff
/* 1B8381C 01C82A00 */ .space 0x40

dlabel gCd
/* 1B8385C 01C82A40 */ .space 0x30

dlabel setGifRegisterMode
/* 1B8388C 01C82A70 */ .space 0x720

dlabel vector.2265
/* 1B83FAC 01C83190 */ .space 0x10

dlabel vector.2270
/* 1B83FBC 01C831A0 */ .space 0x10

dlabel disturb_param.1884
/* 1B83FCC 01C831B0 */ .space 0x10

dlabel MicroProgramEntryPoint
/* 1B83FDC 01C831C0 */ .space 0x20

dlabel screenPrimitiveMatrix
/* 1B83FFC 01C831E0 */ .space 0x40

dlabel screenClipMatrix
/* 1B8403C 01C83220 */ .space 0x40

dlabel return_buffer.1743
/* 1B8407C 01C83260 */ .space 0x10

dlabel v.1748
/* 1B8408C 01C83270 */ .space 0x10

dlabel m.1750
/* 1B8409C 01C83280 */ .space 0x40

dlabel matrix.1755
/* 1B840DC 01C832C0 */ .space 0x40

dlabel return_buffer.1793
/* 1B8411C 01C83300 */ .space 0x10

dlabel return_buffer.1839
/* 1B8412C 01C83310 */ .space 0x40

dlabel return_buffer.1856
/* 1B8416C 01C83350 */ .space 0x40

dlabel return_buffer.1704
/* 1B841AC 01C83390 */ .space 0x40

dlabel giftag.1854
/* 1B841EC 01C833D0 */ .space 0x10

dlabel randomPool
/* 1B841FC 01C833E0 */ .space 0x190

dlabel mendererTime
/* 1B8438C 01C83570 */ .space 0x40

dlabel mendererData
/* 1B843CC 01C835B0 */ .space 0x4B0

dlabel mendererDmaPacket
/* 1B8487C 01C83A60 */ .space 0x60

dlabel restoreDmaPacket
/* 1B848DC 01C83AC0 */ .space 0xC0

dlabel B_1C83B80
/* 1B8499C 01C83B80 */ .space 0x20

dlabel waveStr
/* 1B849BC 01C83BA0 */ .space 0x30

dlabel mendererDeltaRotation
/* 1B849EC 01C83BD0 */ .space 0x20

dlabel alphaWeight
/* 1B84A0C 01C83BF0 */ .space 0x20

dlabel positionData
/* 1B84A2C 01C83C10 */ .space 0xE60

dlabel indexMap
/* 1B8588C 01C84A70 */ .space 0x1D0

dlabel cmnGifTr
/* 1B85A5C 01C84C40 */ .space 0x3880

dlabel camera.2028
/* 1B892DC 01C884C0 */ .space 0x10

dlabel B_1C884D0
/* 1B892EC 01C884D0 */ .space 0x30

dlabel padsif
/* 1B8931C 01C88500 */ .space 0x50

dlabel PadInfo
/* 1B8936C 01C88550 */ .space 0xF0

dlabel dma_iop_data
/* 1B8945C 01C88640 */ .space 0x200

dlabel buffer
/* 1B8965C 01C88840 */ .space 0x80

dlabel q.3
/* 1B896DC 01C888C0 */ .space 0x110

dlabel tinfo
/* 1B897EC 01C889D0 */ .space 0x18

dlabel B_1C889E8
/* 1B89804 01C889E8 */ .space 0x18

dlabel wbuf
/* 1B8981C 01C88A00 */ .space 0x140

dlabel rbuf
/* 1B8995C 01C88B40 */ .space 0x140

dlabel linebuf
/* 1B89A9C 01C88C80 */ .space 0x80

dlabel _pckt_buffer
/* 1B89B1C 01C88D00 */ .space 0x80

dlabel _send_buffer
/* 1B89B9C 01C88D80 */ .space 0x40

dlabel _csdata
/* 1B89BDC 01C88DC0 */ .space 0x14

dlabel sif0_handleid
/* 1B89BF0 01C88DD4 */ .space 0x04

dlabel _data_table
/* 1B89BF4 01C88DD8 */ .space 0x08

dlabel B_1C88DE0
/* 1B89BFC 01C88DE0 */ .space 0x04

dlabel B_1C88DE4
/* 1B89C00 01C88DE4 */ .space 0x08

dlabel B_1C88DEC
/* 1B89C08 01C88DEC */ .space 0x14

dlabel _sys_buffer
/* 1B89C1C 01C88E00 */ .space 0x100

dlabel soft_reg
/* 1B89D1C 01C88F00 */ .space 0x80

dlabel _packet_buffer
/* 1B89D9C 01C88F80 */ .space 0x800

dlabel _free_buffer
/* 1B8A59C 01C89780 */ .space 0x800

dlabel _free_buffer2
/* 1B8AD9C 01C89F80 */ .space 0x800

dlabel _data_table
/* 1B8B59C 01C8A780 */ .space 0x40

dlabel ip0.48
/* 1B8B5DC 01C8A7C0 */ .space 0x40

dlabel _send_data
/* 1B8B61C 01C8A800 */ .space 0xC40

dlabel _rcv_data_rpc
/* 1B8C25C 01C8B440 */ .space 0x40

dlabel _rcv_data_cmd
/* 1B8C29C 01C8B480 */ .space 0x10

dlabel B_1C8B490
/* 1B8C2AC 01C8B490 */ .space 0x04

dlabel B_1C8B494
/* 1B8C2B0 01C8B494 */ .space 0x42C

dlabel _iob
/* 1B8C6DC 01C8B8C0 */ .space 0x200

dlabel _cd
/* 1B8C8DC 01C8BAC0 */ .space 0x28

dlabel _fsversion
/* 1B8C904 01C8BAE8 */ .space 0x18

dlabel _sif_FsRcv_Data
/* 1B8C91C 01C8BB00 */ .space 0x40

dlabel _senddata
/* 1B8C95C 01C8BB40 */ .space 0x08

dlabel B_1C8BB48
/* 1B8C964 01C8BB48 */ .space 0x1F8

dlabel cd
/* 1B8CB5C 01C8BD40 */ .space 0x28

dlabel _lfversion
/* 1B8CB84 01C8BD68 */ .space 0x18

dlabel rdata
/* 1B8CB9C 01C8BD80 */ .space 0x70

dlabel stack.6
/* 1B8CC0C 01C8BDF0 */ .space 0x400

dlabel topSema
/* 1B8D00C 01C8C1F0 */ .space 0x08

dlabel topArg
/* 1B8D014 01C8C1F8 */ .space 0x408

dlabel userarea
/* 1B8D41C 01C8C600 */ .space 0x40

dlabel sceCdCbfunc
/* 1B8D45C 01C8C640 */ .space 0x04

dlabel sceCdPoffCbfunc
/* 1B8D460 01C8C644 */ .space 0x04

dlabel sceCdPoffCbdata
/* 1B8D464 01C8C648 */ .space 0x04

dlabel sceCdPoffCbfunc_num
/* 1B8D468 01C8C64C */ .space 0x04

dlabel my_thid
/* 1B8D46C 01C8C650 */ .space 0x08

dlabel my_th_info
/* 1B8D474 01C8C658 */ .space 0x30

dlabel cb_tp
/* 1B8D4A4 01C8C688 */ .space 0x38

dlabel _sf_data
/* 1B8D4DC 01C8C6C0 */ .space 0x140

dlabel sfrdata
/* 1B8D61C 01C8C800 */ .space 0x40

dlabel cdrdsf
/* 1B8D65C 01C8C840 */ .space 0x28

dlabel cdit
/* 1B8D684 01C8C868 */ .space 0x28

dlabel cddr
/* 1B8D6AC 01C8C890 */ .space 0x30

dlabel _i_mode
/* 1B8D6DC 01C8C8C0 */ .space 0x10

dlabel _dr_mode
/* 1B8D6EC 01C8C8D0 */ .space 0x30

dlabel mcClientID
/* 1B8D71C 01C8C900 */ .space 0x28

dlabel typeAddr
/* 1B8D744 01C8C928 */ .space 0x04

dlabel freeAddr
/* 1B8D748 01C8C92C */ .space 0x04

dlabel formAddr
/* 1B8D74C 01C8C930 */ .space 0x10

dlabel buffFileInfo
/* 1B8D75C 01C8C940 */ .space 0x20

dlabel B_1C8C960
/* 1B8D77C 01C8C960 */ .space 0x20

dlabel sifParamOrd
/* 1B8D79C 01C8C980 */ .space 0x30

dlabel sifParamFname
/* 1B8D7CC 01C8C9B0 */ .space 0x14

dlabel B_1C8C9C4
/* 1B8D7E0 01C8C9C4 */ .space 0x43C

dlabel sifParamNext
/* 1B8DC1C 01C8CE00 */ .space 0xC0

dlabel currentDir
/* 1B8DCDC 01C8CEC0 */ .space 0x1000

dlabel retval
/* 1B8ECDC 01C8DEC0 */ .space 0x40

dlabel initialized.10
/* 1B8ED1C 01C8DF00 */ .space 0x08

dlabel eh.39
/* 1B8ED24 01C8DF08 */ .space 0x10

dlabel initialized.40
/* 1B8ED34 01C8DF18 */ .space 0x08

dlabel top_elt.41
/* 1B8ED3C 01C8DF20 */ .space 0x08

dlabel thenan.3
/* 1B8ED44 01C8DF28 */ .space 0x18

dlabel thenan.3
/* 1B8ED5C 01C8DF40 */ .space 0x10

dlabel objects
/* 1B8ED6C 01C8DF50 */ .space 0x08

dlabel __ti13bad_exception
/* 1B8ED74 01C8DF58 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DF64
/* 1B8ED80 01C8DF64 */ .space 0x04

dlabel __ti9bad_alloc
/* 1B8ED84 01C8DF68 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DF74
/* 1B8ED90 01C8DF74 */ .space 0x04

dlabel __ti10bad_typeid
/* 1B8ED94 01C8DF78 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DF84
/* 1B8EDA0 01C8DF84 */ .space 0x04

dlabel __ti8bad_cast
/* 1B8EDA4 01C8DF88 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DF94
/* 1B8EDB0 01C8DF94 */ .space 0x04

dlabel __ti16__user_type_info
/* 1B8EDB4 01C8DF98 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFA4
/* 1B8EDC0 01C8DFA4 */ .space 0x04

dlabel __ti14__si_type_info
/* 1B8EDC4 01C8DFA8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFB4
/* 1B8EDD0 01C8DFB4 */ .space 0x04

dlabel __ti17__class_type_info
/* 1B8EDD4 01C8DFB8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFC4
/* 1B8EDE0 01C8DFC4 */ .space 0x04

dlabel __ti16__func_type_info
/* 1B8EDE4 01C8DFC8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFD4
/* 1B8EDF0 01C8DFD4 */ .space 0x04

dlabel __ti16__attr_type_info
/* 1B8EDF4 01C8DFD8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFE4
/* 1B8EE00 01C8DFE4 */ .space 0x04

dlabel __ti16__ptmf_type_info
/* 1B8EE04 01C8DFE8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8DFF4
/* 1B8EE10 01C8DFF4 */ .space 0x04

dlabel __ti17__array_type_info
/* 1B8EE14 01C8DFF8 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8E004
/* 1B8EE20 01C8E004 */ .space 0x04

dlabel __ti19__pointer_type_info
/* 1B8EE24 01C8E008 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8E014
/* 1B8EE30 01C8E014 */ .space 0x04

dlabel __ti16__ptmd_type_info
/* 1B8EE34 01C8E018 */ .space 0x0C

# Automatically generated and unreferenced pad
dlabel B_1C8E024
/* 1B8EE40 01C8E024 */ .space 0x04

dlabel __ti19__builtin_type_info
/* 1B8EE44 01C8E028 */ .space 0x0C
