.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64     # allow use of 64-bit general purpose registers

.section .sbss

.align 4

/* Generated by spimdisasm 1.18.0 */

dlabel _fbss
/* 29AA00 00399A00 */ .space 0x08

dlabel MSGCOL
/* 29AA08 00399A08 */ .space 0x01

dlabel B_399A09
/* 29AA09 00399A09 */ .space 0x01

dlabel B_399A0A
/* 29AA0A 00399A0A */ .space 0x06

dlabel MSGSIZE
/* 29AA10 00399A10 */ .space 0x02

dlabel B_399A12
/* 29AA12 00399A12 */ .space 0x02

dlabel MSGZPOP
/* 29AA14 00399A14 */ .space 0x04

dlabel th_id_Ctrl
/* 29AA18 00399A18 */ .space 0x04

dlabel cmngif_pri_cnt
/* 29AA1C 00399A1C */ .space 0x04

dlabel cmnGifPkBase
/* 29AA20 00399A20 */ .space 0x04

dlabel cmnGifPkCurrent
/* 29AA24 00399A24 */ .space 0x04

dlabel cmnGifPkEnd
/* 29AA28 00399A28 */ .space 0x04

dlabel usrMemPosCnt
/* 29AA2C 00399A2C */ .space 0x04

dlabel usrMemPosEndCnt
/* 29AA30 00399A30 */ .space 0x04

dlabel cdSampleTmp
/* 29AA34 00399A34 */ .space 0x04

dlabel follow_scr_tap_memory_cnt
/* 29AA38 00399A38 */ .space 0x04

dlabel follow_scr_tap_memory_cnt_load
/* 29AA3C 00399A3C */ .space 0x04

dlabel commake_str_cnt
/* 29AA40 00399A40 */ .space 0x04

dlabel sprDmaC
/* 29AA44 00399A44 */ .space 0x04

dlabel kanji_pp
/* 29AA48 00399A48 */ .space 0x04

dlabel dr_tap_req_num
/* 29AA4C 00399A4C */ .space 0x04

dlabel scenectrl_outside_cnt
/* 29AA50 00399A50 */ .space 0x04

dlabel scenectrl_outside_read_cnt
/* 29AA54 00399A54 */ .space 0x04

dlabel mozaiku_poll_str_current_pp
/* 29AA58 00399A58 */ .space 0x04

dlabel drawCurrentLine
/* 29AA5C 00399A5C */ .space 0x04

dlabel drawCurrentTime
/* 29AA60 00399A60 */ .space 0x04

dlabel drawCurrentTimeOld
/* 29AA64 00399A64 */ .space 0x04

dlabel drawEventrec
/* 29AA68 00399A68 */ .space 0x04

dlabel useDispFlag
/* 29AA6C 00399A6C */ .space 0x04

dlabel drDispFlag
/* 29AA70 00399A70 */ .space 0x04

dlabel men_ctrl_ratio
/* 29AA74 00399A74 */ .space 0x04

dlabel men_ctrl_enum
/* 29AA78 00399A78 */ .space 0x04

dlabel ddbg_pause_f
/* 29AA7C 00399A7C */ .space 0x04

dlabel exam_global_ply_current
/* 29AA80 00399A80 */ .space 0x04

dlabel mbar_ctrl_time
/* 29AA84 00399A84 */ .space 0x04

dlabel mbar_ctrl_stage
/* 29AA88 00399A88 */ .space 0x04

dlabel mbar_ctrl_stage_selT
/* 29AA8C 00399A8C */ .space 0x04

dlabel guime_hdl
/* 29AA90 00399A90 */ .space 0x04

dlabel guime_camera_hdl
/* 29AA94 00399A94 */ .space 0x04

dlabel ldmap_hdl
/* 29AA98 00399A98 */ .space 0x08

dlabel mc_holdTmp
/* 29AAA0 00399AA0 */ .space 0x08

dlabel mc_resetTmp
/* 29AAA8 00399AA8 */ .space 0x04

dlabel p3str_pp
/* 29AAAC 00399AAC */ .space 0x04

dlabel adrd_common
/* 29AAB0 00399AB0 */ .space 0x04

dlabel adrd_common_cnt
/* 29AAB4 00399AB4 */ .space 0x04

dlabel p3str_sort_cnt
/* 29AAB8 00399AB8 */ .space 0x04

dlabel bFirst
/* 29AABC 00399ABC */ .space 0x04

dlabel VsLev
/* 29AAC0 00399AC0 */ .space 0x04

dlabel AMusicFitTime
/* 29AAC4 00399AC4 */ .space 0x04

dlabel state.248
/* 29AAC8 00399AC8 */ .space 0x04

dlabel mesNo.249
/* 29AACC 00399ACC */ .space 0x04

dlabel state.253
/* 29AAD0 00399AD0 */ .space 0x04

dlabel state.264
/* 29AAD4 00399AD4 */ .space 0x04

dlabel saveSel.265
/* 29AAD8 00399AD8 */ .space 0x04

dlabel waitTime.266
/* 29AADC 00399ADC */ .space 0x04

dlabel state.270
/* 29AAE0 00399AE0 */ .space 0x04

dlabel waitTime.271
/* 29AAE4 00399AE4 */ .space 0x04

dlabel scstate.273
/* 29AAE8 00399AE8 */ .space 0x04

dlabel scstPos.274
/* 29AAEC 00399AEC */ .space 0x04

dlabel curTag.275
/* 29AAF0 00399AF0 */ .space 0x04

dlabel fphs_pos.276
/* 29AAF4 00399AF4 */ .space 0x04

dlabel AnmBit.277
/* 29AAF8 00399AF8 */ .space 0x04

dlabel state.296
/* 29AAFC 00399AFC */ .space 0x04

dlabel scstate.433
/* 29AB00 00399B00 */ .space 0x04

dlabel scstPos.434
/* 29AB04 00399B04 */ .space 0x04

dlabel opt_lang.459
/* 29AB08 00399B08 */ .space 0x04

dlabel opt_subt.460
/* 29AB0C 00399B0C */ .space 0x04

dlabel opt_vibr.461
/* 29AB10 00399B10 */ .space 0x04

dlabel opt_oneb.462
/* 29AB14 00399B14 */ .space 0x04

dlabel pP3GameState
/* 29AB18 00399B18 */ .space 0x04

dlabel _bMapCaptureReq
/* 29AB1C 00399B1C */ .space 0x04

dlabel _MNwaitTime
/* 29AB20 00399B20 */ .space 0x04

dlabel CurMapOldFlg
/* 29AB24 00399B24 */ .space 0x04

dlabel CurMapNo
/* 29AB28 00399B28 */ .space 0x04

dlabel CurMapBakFlg
/* 29AB2C 00399B2C */ .space 0x04

dlabel CurMapState
/* 29AB30 00399B30 */ .space 0x04

dlabel UserWork
/* 29AB34 00399B34 */ .space 0x04

dlabel pCStageRank
/* 29AB38 00399B38 */ .space 0x04

dlabel UserLst
/* 29AB3C 00399B3C */ .space 0x04

dlabel UserDispWork
/* 29AB40 00399B40 */ .space 0x04

dlabel UCheckLoadError
/* 29AB44 00399B44 */ .space 0x04

dlabel UCheckSaveError
/* 29AB48 00399B48 */ .space 0x04

dlabel subStatus
/* 29AB4C 00399B4C */ .space 0x04

dlabel ret
/* 29AB50 00399B50 */ .space 0x04

dlabel errorNo
/* 29AB54 00399B54 */ .space 0x04

dlabel waitTime
/* 29AB58 00399B58 */ .space 0x04

dlabel pGameData
/* 29AB5C 00399B5C */ .space 0x04

dlabel FreeSizeFlg
/* 29AB60 00399B60 */ .space 0x04

dlabel portCheckFlg
/* 29AB64 00399B64 */ .space 0x04

dlabel NeedSize
/* 29AB68 00399B68 */ .space 0x04

dlabel B_399B6C
/* 29AB6C 00399B6C */ .space 0x04

dlabel UChkSize
/* 29AB70 00399B70 */ .space 0x04

dlabel B_399B74
/* 29AB74 00399B74 */ .space 0x04

dlabel isFileFlgCash
/* 29AB78 00399B78 */ .space 0x04

dlabel _AnimeFontFlg
/* 29AB7C 00399B7C */ .space 0x04

dlabel kanji_pp
/* 29AB80 00399B80 */ .space 0x04

dlabel _PkScrW
/* 29AB84 00399B84 */ .space 0x04

dlabel _PkScrH
/* 29AB88 00399B88 */ .space 0x04

dlabel workAreaSize
/* 29AB8C 00399B8C */ .space 0x04

dlabel debugParam
/* 29AB90 00399B90 */ .space 0x04

dlabel AwfulStatus
/* 29AB94 00399B94 */ .space 0x04

dlabel MendererCreateTextureEntryPoint
/* 29AB98 00399B98 */ .space 0x04

dlabel MendererDrawMeshEntryPoint
/* 29AB9C 00399B9C */ .space 0x04

dlabel return_buffer.1822
/* 29ABA0 00399BA0 */ .space 0x04

dlabel return_buffer.1826
/* 29ABA4 00399BA4 */ .space 0x04

dlabel noodleStatus
/* 29ABA8 00399BA8 */ .space 0x04

dlabel noodleChangeTimer
/* 29ABAC 00399BAC */ .space 0x04

dlabel noodleDeltaRotation
/* 29ABB0 00399BB0 */ .space 0x04

dlabel mendererBackgroundPicture
/* 29ABB4 00399BB4 */ .space 0x04

dlabel mendererAwfulColor
/* 29ABB8 00399BB8 */ .space 0x04

dlabel awfulStatus
/* 29ABBC 00399BBC */ .space 0x04

dlabel awfulChangeTimer
/* 29ABC0 00399BC0 */ .space 0x04

dlabel awfulRotation
/* 29ABC4 00399BC4 */ .space 0x04

dlabel WV_SCREEN_W
/* 29ABC8 00399BC8 */ .space 0x04

dlabel WV_SCREEN_H
/* 29ABCC 00399BCC */ .space 0x04

dlabel __ti9exception
/* 29ABD0 00399BD0 */ .space 0x08

dlabel __ti9type_info
/* 29ABD8 00399BD8 */ .space 0x08

dlabel errno
/* 29ABE0 00399BE0 */ .space 0x04
