.include "macro.inc"

.section .sdata

.align 4

/* Generated by spimdisasm 1.26.1 */

dlabel __main_reference, global
/* 29A300 00399300 B0801600 */ .word __main
.size __main_reference, . - __main_reference

/* Automatically generated and unreferenced pad */
dlabel D_00399304
/* 29A304 00399304 00000000 */ .word 0x00000000
.size D_00399304, . - D_00399304

.align 3
dlabel D_STR_00399308
/* 29A308 00399308 */ .asciz "host:%s"
.align 2
.size D_STR_00399308, . - D_STR_00399308

dlabel mtcCurrentTask, global
/* 29A310 00399310 00000000 */ .word 0x00000000
.size mtcCurrentTask, . - mtcCurrentTask

dlabel mtcSemaEnd, global
/* 29A314 00399314 00000000 */ .word 0x00000000
.size mtcSemaEnd, . - mtcSemaEnd

.align 3
dlabel D_STR_00399318
/* 29A318 00399318 */ .asciz "%03u"
.align 2
.size D_STR_00399318, . - D_STR_00399318

.align 3
dlabel D_STR_00399320
/* 29A320 00399320 */ .asciz "%u"
.align 2
/* 29A324 00399324 */ .asciz ""
.align 2
.size D_STR_00399320, . - D_STR_00399320

dlabel D_00399328
/* 29A328 00399328 */ .byte 0x28
/* 29A329 00399329 */ .byte 0x62
/* 29A32A 0039932A */ .byte 0x79
/* 29A32B 0039932B */ .byte 0x74
/* 29A32C 0039932C */ .byte 0x65
/* 29A32D 0039932D */ .byte 0x29
/* 29A32E 0039932E */ .byte 0x00
/* 29A32F 0039932F */ .byte 0x00
.size D_00399328, . - D_00399328

dlabel double_tmp_on_off, global
/* 29A330 00399330 00000000 */ .word 0x00000000
.size double_tmp_on_off, . - double_tmp_on_off

dlabel _end_addr, local
/* 29A334 00399334 00E8DD01 */ .word D_01DDE800
.size _end_addr, . - _end_addr

dlabel _stack_size_addr, local
/* 29A338 00399338 00800000 */ .word 0x00008000
.size _stack_size_addr, . - _stack_size_addr

dlabel outbuf_idx, global
/* 29A33C 0039933C 00000000 */ .word 0x00000000
.size outbuf_idx, . - outbuf_idx

dlabel oddeven_idx, global
/* 29A340 00399340 00000000 */ .word 0x00000000
.size oddeven_idx, . - oddeven_idx

dlabel OsFuncAddr, global
/* 29A344 00399344 00000000 */ .word 0x00000000
.size OsFuncAddr, . - OsFuncAddr

dlabel hat_change_enum, global
/* 29A348 00399348 00000000 */ .word 0x00000000
.size hat_change_enum, . - hat_change_enum

/* Automatically generated and unreferenced pad */
dlabel D_0039934C
/* 29A34C 0039934C 00000000 */ .word 0x00000000
.size D_0039934C, . - D_0039934C

.align 3
dlabel D_STR_00399350
/* 29A350 00399350 */ .asciz "TIM2"
.align 2
.size D_STR_00399350, . - D_STR_00399350

.align 3
dlabel D_STR_00399358
/* 29A358 00399358 */ .asciz "CLT2"
.align 2
.size D_STR_00399358, . - D_STR_00399358

dlabel current_intg_adrs, global
/* 29A360 00399360 00000000 */ .word 0x00000000
.size current_intg_adrs, . - current_intg_adrs

/* Automatically generated and unreferenced pad */
dlabel D_00399364
/* 29A364 00399364 00000000 */ .word 0x00000000
.size D_00399364, . - D_00399364

dlabel D_00399368
/* 29A368 00399368 00010000 */ .word 0x00000100
.size D_00399368, . - D_00399368

dlabel time_tmp_max.174, local
/* 29A36C 0039936C 00000000 */ .word 0x00000000
.size time_tmp_max.174, . - time_tmp_max.174

dlabel sndFadeTime, local
/* 29A370 00399370 00000000 */ .word 0x00000000
.size sndFadeTime, . - sndFadeTime

/* Automatically generated and unreferenced pad */
dlabel D_00399374
/* 29A374 00399374 00000000 */ .word 0x00000000
.size D_00399374, . - D_00399374

.align 3
dlabel D_STR_00399378
/* 29A378 00399378 */ .asciz "TITLE"
.align 2
.size D_STR_00399378, . - D_STR_00399378

.align 3
dlabel D_STR_00399380
/* 29A380 00399380 */ .asciz "GAME 0"
.align 2
.size D_STR_00399380, . - D_STR_00399380

.align 3
dlabel D_STR_00399388
/* 29A388 00399388 */ .asciz "HOOK 0"
.align 2
.size D_STR_00399388, . - D_STR_00399388

.align 3
dlabel D_STR_00399390
/* 29A390 00399390 */ .asciz "BONUS"
.align 2
.size D_STR_00399390, . - D_STR_00399390

.align 3
dlabel D_STR_00399398
/* 29A398 00399398 */ .asciz "VS 0"
.align 2
.size D_STR_00399398, . - D_STR_00399398

.align 3
dlabel D_STR_003993A0
/* 29A3A0 003993A0 */ .asciz "VS 8"
.align 2
.size D_STR_003993A0, . - D_STR_003993A0

.align 3
dlabel D_STR_003993A8
/* 29A3A8 003993A8 */ .asciz "VS 7"
.align 2
.size D_STR_003993A8, . - D_STR_003993A8

.align 3
dlabel D_STR_003993B0
/* 29A3B0 003993B0 */ .asciz "VS 6"
.align 2
.size D_STR_003993B0, . - D_STR_003993B0

.align 3
dlabel D_STR_003993B8
/* 29A3B8 003993B8 */ .asciz "VS 5"
.align 2
.size D_STR_003993B8, . - D_STR_003993B8

.align 3
dlabel D_STR_003993C0
/* 29A3C0 003993C0 */ .asciz "VS 4"
.align 2
.size D_STR_003993C0, . - D_STR_003993C0

.align 3
dlabel D_STR_003993C8
/* 29A3C8 003993C8 */ .asciz "VS 3"
.align 2
.size D_STR_003993C8, . - D_STR_003993C8

.align 3
dlabel D_STR_003993D0
/* 29A3D0 003993D0 */ .asciz "VS 2"
.align 2
.size D_STR_003993D0, . - D_STR_003993D0

.align 3
dlabel D_STR_003993D8
/* 29A3D8 003993D8 */ .asciz "VS 1"
.align 2
.size D_STR_003993D8, . - D_STR_003993D8

.align 3
dlabel D_STR_003993E0
/* 29A3E0 003993E0 */ .asciz "STAGE 9"
.align 2
.size D_STR_003993E0, . - D_STR_003993E0

.align 3
dlabel D_STR_003993E8
/* 29A3E8 003993E8 */ .asciz "STAGE 8"
.align 2
.size D_STR_003993E8, . - D_STR_003993E8

.align 3
dlabel D_STR_003993F0
/* 29A3F0 003993F0 */ .asciz "STAGE 7"
.align 2
.size D_STR_003993F0, . - D_STR_003993F0

.align 3
dlabel D_STR_003993F8
/* 29A3F8 003993F8 */ .asciz "STAGE 6"
.align 2
.size D_STR_003993F8, . - D_STR_003993F8

.align 3
dlabel D_STR_00399400
/* 29A400 00399400 */ .asciz "STAGE 5"
.align 2
.size D_STR_00399400, . - D_STR_00399400

.align 3
dlabel D_STR_00399408
/* 29A408 00399408 */ .asciz "STAGE 4"
.align 2
.size D_STR_00399408, . - D_STR_00399408

.align 3
dlabel D_STR_00399410
/* 29A410 00399410 */ .asciz "STAGE 3"
.align 2
.size D_STR_00399410, . - D_STR_00399410

.align 3
dlabel D_STR_00399418
/* 29A418 00399418 */ .asciz "STAGE 2"
.align 2
.size D_STR_00399418, . - D_STR_00399418

.align 3
dlabel D_STR_00399420
/* 29A420 00399420 */ .asciz "STAGE 1"
.align 2
.size D_STR_00399420, . - D_STR_00399420

.align 3
dlabel D_STR_00399428
/* 29A428 00399428 */ .asciz "STAGE 0"
.align 2
.size D_STR_00399428, . - D_STR_00399428

dlabel stdat_rec_num, global
/* 29A430 00399430 14000000 */ .word 0x00000014
.size stdat_rec_num, . - stdat_rec_num

/* Automatically generated and unreferenced pad */
dlabel D_00399434
/* 29A434 00399434 00000000 */ .word 0x00000000
.size D_00399434, . - D_00399434

dlabel titleStartKey, local
/* 29A438 00399438 00000000 */ .word 0x00000000
.size titleStartKey, . - titleStartKey

dlabel fadeoutStartKey, local
/* 29A43C 0039943C 00000000 */ .word 0x00000000
.size fadeoutStartKey, . - fadeoutStartKey

dlabel gameEndWaitLoop, local
/* 29A440 00399440 00000000 */ .word 0x00000000
.size gameEndWaitLoop, . - gameEndWaitLoop

dlabel replayGuiOffFlag, local
/* 29A444 00399444 00000000 */ .word 0x00000000
.size replayGuiOffFlag, . - replayGuiOffFlag

dlabel jimakuWakuOff, local
/* 29A448 00399448 00000000 */ .word 0x00000000
.size jimakuWakuOff, . - jimakuWakuOff

dlabel currentTblNumber, global
/* 29A44C 0039944C 00000000 */ .word 0x00000000
.size currentTblNumber, . - currentTblNumber

dlabel vs_tapdat_tmp_cnt, global
/* 29A450 00399450 00000000 */ .word 0x00000000
.size vs_tapdat_tmp_cnt, . - vs_tapdat_tmp_cnt

dlabel scrJimakuLine, global
/* 29A454 00399454 00000000 */ .word 0x00000000
.size scrJimakuLine, . - scrJimakuLine

dlabel scrDrawLine, global
/* 29A458 00399458 00000000 */ .word 0x00000000
.size scrDrawLine, . - scrDrawLine

dlabel scrMbarLine, global
/* 29A45C 0039945C 00000000 */ .word 0x00000000
.size scrMbarLine, . - scrMbarLine

dlabel scrRefLineTime, global
/* 29A460 00399460 FFFFFFFF */ .word 0xFFFFFFFF
.size scrRefLineTime, . - scrRefLineTime

/* Automatically generated and unreferenced pad */
dlabel D_00399464
/* 29A464 00399464 00000000 */ .word 0x00000000
.size D_00399464, . - D_00399464

dlabel D_00399468
/* 29A468 00399468 10110100 */ .word 0x00011110
/* 29A46C 0039946C 00000000 */ .word 0x00000000
.size D_00399468, . - D_00399468

dlabel D_00399470
/* 29A470 00399470 06090F12 */ .word 0x120F0906
/* 29A474 00399474 00000000 */ .word 0x00000000
/* 29A478 00399478 42415345 */ .word 0x45534142
/* 29A47C 0039947C 00000000 */ .word 0x00000000
/* 29A480 00399480 4C563100 */ .word 0x0031564C
/* 29A484 00399484 00000000 */ .word 0x00000000
/* 29A488 00399488 4C563200 */ .word 0x0032564C
/* 29A48C 0039948C 00000000 */ .word 0x00000000
/* 29A490 00399490 4C563300 */ .word 0x0033564C
/* 29A494 00399494 00000000 */ .word 0x00000000
/* 29A498 00399498 4C563400 */ .word 0x0034564C
/* 29A49C 0039949C 00000000 */ .word 0x00000000
/* 29A4A0 003994A0 4C563500 */ .word 0x0035564C
/* 29A4A4 003994A4 00000000 */ .word 0x00000000
/* 29A4A8 003994A8 4C563600 */ .word 0x0036564C
/* 29A4AC 003994AC 00000000 */ .word 0x00000000
/* 29A4B0 003994B0 4C563700 */ .word 0x0037564C
/* 29A4B4 003994B4 00000000 */ .word 0x00000000
/* 29A4B8 003994B8 4C563800 */ .word 0x0038564C
/* 29A4BC 003994BC 00000000 */ .word 0x00000000
/* 29A4C0 003994C0 4C563900 */ .word RO_STR_0039564C
/* 29A4C4 003994C4 00000000 */ .word 0x00000000
/* 29A4C8 003994C8 4C563130 */ .word 0x3031564C
/* 29A4CC 003994CC 00000000 */ .word 0x00000000
/* 29A4D0 003994D0 4C563131 */ .word 0x3131564C
/* 29A4D4 003994D4 00000000 */ .word 0x00000000
/* 29A4D8 003994D8 4C563132 */ .word 0x3231564C
/* 29A4DC 003994DC 00000000 */ .word 0x00000000
/* 29A4E0 003994E0 4C563133 */ .word 0x3331564C
/* 29A4E4 003994E4 00000000 */ .word 0x00000000
/* 29A4E8 003994E8 4C563134 */ .word 0x3431564C
/* 29A4EC 003994EC 00000000 */ .word 0x00000000
/* 29A4F0 003994F0 4C563135 */ .word 0x3531564C
/* 29A4F4 003994F4 00000000 */ .word 0x00000000
/* 29A4F8 003994F8 4C563136 */ .word 0x3631564C
/* 29A4FC 003994FC 00000000 */ .word 0x00000000
.size D_00399470, . - D_00399470

dlabel dbgmsg_on_off.360, local
/* 29A500 00399500 01000000 */ .word 0x00000001
.size dbgmsg_on_off.360, . - dbgmsg_on_off.360

dlabel sprSetNum, local
/* 29A504 00399504 00000000 */ .word 0x00000000
.size sprSetNum, . - sprSetNum

dlabel SUBT_POSX, global
/* 29A508 00399508 00080000 */ .word 0x00000800
.size SUBT_POSX, . - SUBT_POSX

dlabel SUBT_POSY, global
/* 29A50C 0039950C 32080000 */ .word 0x00000832
.size SUBT_POSY, . - SUBT_POSY

dlabel subtSetNum, local
/* 29A510 00399510 00000000 */ .word 0x00000000
.size subtSetNum, . - subtSetNum

/* Automatically generated and unreferenced pad */
dlabel D_00399514
/* 29A514 00399514 00000000 */ .word 0x00000000
.size D_00399514, . - D_00399514

dlabel vclr_black_tmp, local
/* 29A518 00399518 00000000 */ .word 0x00000000
.size vclr_black_tmp, . - vclr_black_tmp

dlabel bthrow_ctrl_time, local
/* 29A51C 0039951C 00000000 */ .word 0x00000000
.size bthrow_ctrl_time, . - bthrow_ctrl_time

.align 3
dlabel D_STR_00399520
/* 29A520 00399520 */ .asciz "nome_"
.align 2
.size D_STR_00399520, . - D_STR_00399520

dlabel mend_title_req, local
/* 29A528 00399528 00000000 */ .word 0x00000000
.size mend_title_req, . - mend_title_req

dlabel ddbg_event_num, local
/* 29A52C 0039952C 00000000 */ .word 0x00000000
.size ddbg_event_num, . - ddbg_event_num

dlabel ddbg_scene_num, local
/* 29A530 00399530 00000000 */ .word 0x00000000
.size ddbg_scene_num, . - ddbg_scene_num

dlabel ddbg_go_event_scene, local
/* 29A534 00399534 00000000 */ .word 0x00000000
.size ddbg_go_event_scene, . - ddbg_go_event_scene

dlabel ddbg_tap_num, local
/* 29A538 00399538 00000000 */ .word 0x00000000
.size ddbg_tap_num, . - ddbg_tap_num

dlabel ddbg_bmp_frame, local
/* 29A53C 0039953C 00000000 */ .word 0x00000000
.size ddbg_bmp_frame, . - ddbg_bmp_frame

.align 3
dlabel D_STR_00399540
/* 29A540 00399540 */ .asciz "#%02X"
.align 2
.size D_STR_00399540, . - D_STR_00399540

.align 3
dlabel D_STR_00399548
/* 29A548 00399548 */ .asciz "BMP OUT"
.align 2
.size D_STR_00399548, . - D_STR_00399548

dlabel ANI_BLUMOVE_ENUM, global
/* 29A550 00399550 00000000 */ .word 0x00000000
.size ANI_BLUMOVE_ENUM, . - ANI_BLUMOVE_ENUM

/* Automatically generated and unreferenced pad */
dlabel D_00399554
/* 29A554 00399554 00000000 */ .word 0x00000000
.size D_00399554, . - D_00399554

dlabel niko_chan_str_pp, local
/* 29A558 00399558 00000000 */ .word 0x00000000
.size niko_chan_str_pp, . - niko_chan_str_pp

dlabel niko_chan_str_cnt, local
/* 29A55C 0039955C 00000000 */ .word 0x00000000
.size niko_chan_str_cnt, . - niko_chan_str_cnt

dlabel hook_use_flag, local
/* 29A560 00399560 00000000 */ .word 0x00000000
.size hook_use_flag, . - hook_use_flag

dlabel exam_disp_cursor_timer, local
/* 29A564 00399564 FFFFFFFF */ .word 0xFFFFFFFF
.size exam_disp_cursor_timer, . - exam_disp_cursor_timer

dlabel scoreTentouFlag, local
/* 29A568 00399568 00000000 */ .word 0x00000000
.size scoreTentouFlag, . - scoreTentouFlag

dlabel otehonAniCnt, local
/* 29A56C 0039956C 00000000 */ .word 0x00000000
.size otehonAniCnt, . - otehonAniCnt

dlabel othon_frame, local
/* 29A570 00399570 00000000 */ .word 0x00000000
.size othon_frame, . - othon_frame

dlabel vs_mouse_disp_flag, local
/* 29A574 00399574 00000000 */ .word 0x00000000
.size vs_mouse_disp_flag, . - vs_mouse_disp_flag

dlabel mbar_pos_y_ofs, local
/* 29A578 00399578 00000000 */ .word 0x00000000
.size mbar_pos_y_ofs, . - mbar_pos_y_ofs

/* Automatically generated and unreferenced pad */
dlabel D_0039957C
/* 29A57C 0039957C 00000000 */ .word 0x00000000
.size D_0039957C, . - D_0039957C

.align 3
dlabel D_STR_00399580
/* 29A580 00399580 */ .asciz "gui"
.align 2
.size D_STR_00399580, . - D_STR_00399580

dlabel SCR_TENMETU_ENUM, global
/* 29A584 00399584 00000000 */ .word 0x00000000
.size SCR_TENMETU_ENUM, . - SCR_TENMETU_ENUM

.align 3
dlabel D_STR_00399588
/* 29A588 00399588 */ .asciz "2p com\n"
.align 2
.size D_STR_00399588, . - D_STR_00399588

dlabel usrSceneHandle, local
/* 29A590 00399590 00000000 */ .word 0x00000000
.size usrSceneHandle, . - usrSceneHandle

/* Automatically generated and unreferenced pad */
dlabel D_00399594
/* 29A594 00399594 00000000 */ .word 0x00000000
.size D_00399594, . - D_00399594

dlabel wipe_type, local
/* 29A598 00399598 00000000 */ .word 0x00000000
.size wipe_type, . - wipe_type

dlabel wipe_end_flag, local
/* 29A59C 0039959C 01000000 */ .word 0x00000001
.size wipe_end_flag, . - wipe_end_flag

dlabel loading_wipe_switch, local
/* 29A5A0 003995A0 00000000 */ .word 0x00000000
.size loading_wipe_switch, . - loading_wipe_switch

dlabel ldmove_rate, local
/* 29A5A4 003995A4 00000000 */ .word 0x00000000
.size ldmove_rate, . - ldmove_rate

dlabel ldrecode_rate, local
/* 29A5A8 003995A8 00000000 */ .word 0x00000000
.size ldrecode_rate, . - ldrecode_rate

dlabel ldlogo_rate, local
/* 29A5AC 003995AC 00000000 */ .word 0x00000000
.size ldlogo_rate, . - ldlogo_rate

dlabel D_003995B0
/* 29A5B0 003995B0 80808080 */ .word 0x80808080
/* 29A5B4 003995B4 00000000 */ .word 0x00000000
.size D_003995B0, . - D_003995B0

.align 3
dlabel D_STR_003995B8
/* 29A5B8 003995B8 */ .asciz "wipe"
.align 2
.size D_STR_003995B8, . - D_STR_003995B8

dlabel wipe_para_spa_type, local
/* 29A5C0 003995C0 00000000 */ .word 0x00000000
.size wipe_para_spa_type, . - wipe_para_spa_type

/* Automatically generated and unreferenced pad */
dlabel D_003995C4
/* 29A5C4 003995C4 00000000 */ .word 0x00000000
.size D_003995C4, . - D_003995C4

dlabel vclr_para_disp, local
/* 29A5C8 003995C8 */ .byte 0xFF
/* 29A5C9 003995C9 */ .byte 0xFF
/* 29A5CA 003995CA */ .byte 0xFF
/* 29A5CB 003995CB */ .byte 0x00
.size vclr_para_disp, . - vclr_para_disp

/* Automatically generated and unreferenced pad */
dlabel D_003995CC
/* 29A5CC 003995CC 00000000 */ .word 0x00000000
.size D_003995CC, . - D_003995CC

dlabel urawaza_skip_bottun, local
/* 29A5D0 003995D0 00000000 */ .word 0x00000000
.size urawaza_skip_bottun, . - urawaza_skip_bottun

dlabel urawaza_levelsel_bottun, local
/* 29A5D4 003995D4 FFFFFFFF */ .word 0xFFFFFFFF
.size urawaza_levelsel_bottun, . - urawaza_levelsel_bottun

.align 3
/* Automatically generated and unreferenced pad */
dlabel D_STR_003995D8
/* 29A5D8 003995D8 */ .asciz "LV16"
.align 2
.size D_STR_003995D8, . - D_STR_003995D8

.align 3
dlabel D_STR_003995E0
/* 29A5E0 003995E0 */ .asciz "LV15"
.align 2
.size D_STR_003995E0, . - D_STR_003995E0

.align 3
dlabel D_STR_003995E8
/* 29A5E8 003995E8 */ .asciz "LV14"
.align 2
.size D_STR_003995E8, . - D_STR_003995E8

.align 3
dlabel D_STR_003995F0
/* 29A5F0 003995F0 */ .asciz "LV13"
.align 2
.size D_STR_003995F0, . - D_STR_003995F0

.align 3
dlabel D_STR_003995F8
/* 29A5F8 003995F8 */ .asciz "LV12"
.align 2
.size D_STR_003995F8, . - D_STR_003995F8

.align 3
dlabel D_STR_00399600
/* 29A600 00399600 */ .asciz "LV11"
.align 2
.size D_STR_00399600, . - D_STR_00399600

.align 3
dlabel D_STR_00399608
/* 29A608 00399608 */ .asciz "LV10"
.align 2
.size D_STR_00399608, . - D_STR_00399608

.align 3
dlabel D_STR_00399610
/* 29A610 00399610 */ .asciz "LV9"
.align 2
/* 29A614 00399614 */ .asciz ""
.align 2
.size D_STR_00399610, . - D_STR_00399610

.align 3
dlabel D_STR_00399618
/* 29A618 00399618 */ .asciz "LV8"
.align 2
/* 29A61C 0039961C */ .asciz ""
.align 2
.size D_STR_00399618, . - D_STR_00399618

.align 3
dlabel D_STR_00399620
/* 29A620 00399620 */ .asciz "LV7"
.align 2
/* 29A624 00399624 */ .asciz ""
.align 2
.size D_STR_00399620, . - D_STR_00399620

.align 3
dlabel D_STR_00399628
/* 29A628 00399628 */ .asciz "LV6"
.align 2
/* 29A62C 0039962C */ .asciz ""
.align 2
.size D_STR_00399628, . - D_STR_00399628

.align 3
dlabel D_STR_00399630
/* 29A630 00399630 */ .asciz "LV5"
.align 2
/* 29A634 00399634 */ .asciz ""
.align 2
.size D_STR_00399630, . - D_STR_00399630

.align 3
dlabel D_STR_00399638
/* 29A638 00399638 */ .asciz "LV4"
.align 2
/* 29A63C 0039963C */ .asciz ""
.align 2
.size D_STR_00399638, . - D_STR_00399638

.align 3
dlabel D_STR_00399640
/* 29A640 00399640 */ .asciz "LV3"
.align 2
/* 29A644 00399644 */ .asciz ""
.align 2
.size D_STR_00399640, . - D_STR_00399640

.align 3
dlabel D_STR_00399648
/* 29A648 00399648 */ .asciz "LV2"
.align 2
/* 29A64C 0039964C */ .asciz ""
.align 2
.size D_STR_00399648, . - D_STR_00399648

.align 3
dlabel D_STR_00399650
/* 29A650 00399650 */ .asciz "LV1"
.align 2
/* 29A654 00399654 */ .asciz ""
.align 2
.size D_STR_00399650, . - D_STR_00399650

.align 3
dlabel D_STR_00399658
/* 29A658 00399658 */ .asciz "BASE"
.align 2
.size D_STR_00399658, . - D_STR_00399658

.align 3
dlabel D_STR_00399660
/* 29A660 00399660 */ .asciz "AUTO"
.align 2
.size D_STR_00399660, . - D_STR_00399660

.align 3
dlabel D_STR_00399668
/* 29A668 00399668 */ .asciz "ON"
.align 2
/* 29A66C 0039966C */ .asciz ""
.align 2
.size D_STR_00399668, . - D_STR_00399668

.align 3
dlabel D_STR_00399670
/* 29A670 00399670 */ .asciz "OFF"
.align 2
/* 29A674 00399674 */ .asciz ""
.align 2
.size D_STR_00399670, . - D_STR_00399670

.align 3
dlabel D_STR_00399678
/* 29A678 00399678 */ .asciz "TABLE"
.align 2
.size D_STR_00399678, . - D_STR_00399678

.align 3
dlabel D_STR_00399680
/* 29A680 00399680 */ .asciz "START"
.align 2
.size D_STR_00399680, . - D_STR_00399680

dlabel overlay_loadaddr, global
/* 29A688 00399688 0000CA01 */ .word 0x01CA0000
.size overlay_loadaddr, . - overlay_loadaddr

/* Automatically generated and unreferenced pad */
dlabel D_0039968C
/* 29A68C 0039968C 00000000 */ .word 0x00000000
/* 29A690 00399690 53494E47 */ .word 0x474E4953
/* 29A694 00399694 4C450000 */ .word 0x0000454C
/* 29A698 00399698 5653204D */ .word 0x4D205356
/* 29A69C 0039969C 414E0000 */ .word 0x00004E41
/* 29A6A0 003996A0 56532043 */ .word 0x43205356
/* 29A6A4 003996A4 4F4D0000 */ .word 0x00004D4F
.size D_0039968C, . - D_0039968C

.align 3
dlabel D_STR_003996A8
/* 29A6A8 003996A8 */ .asciz "NORMAL"
.align 2
.size D_STR_003996A8, . - D_STR_003996A8

.align 3
dlabel D_STR_003996B0
/* 29A6B0 003996B0 */ .asciz "EASY"
.align 2
.size D_STR_003996B0, . - D_STR_003996B0

dlabel D_003996B8
/* 29A6B8 003996B8 A8963900 */ .word D_STR_003996A8
/* 29A6BC 003996BC B0963900 */ .word D_STR_003996B0
.size D_003996B8, . - D_003996B8

.align 3
dlabel D_STR_003996C0
/* 29A6C0 003996C0 */ .asciz "DEBUG"
.align 2
.size D_STR_003996C0, . - D_STR_003996C0

dlabel uramen_end_flag, local
/* 29A6C8 003996C8 00000000 */ .word 0x00000000
.size uramen_end_flag, . - uramen_end_flag

/* Automatically generated and unreferenced pad */
dlabel D_003996CC
/* 29A6CC 003996CC 00000000 */ .word 0x00000000
.size D_003996CC, . - D_003996CC

.align 3
dlabel D_STR_003996D0
/* 29A6D0 003996D0 */ .asciz "ura:%d"
.align 2
.size D_STR_003996D0, . - D_STR_003996D0

dlabel first_f.124, local
/* 29A6D8 003996D8 01000000 */ .word 0x00000001
.size first_f.124, . - first_f.124

/* Automatically generated and unreferenced pad */
dlabel D_003996DC
/* 29A6DC 003996DC 00000000 */ .word 0x00000000
.size D_003996DC, . - D_003996DC

dlabel current_time_old, local
/* 29A6E0 003996E0 00000000 */ .word 0x00000000
.size current_time_old, . - current_time_old

/* Automatically generated and unreferenced pad */
dlabel D_003996E4
/* 29A6E4 003996E4 00000000 */ .word 0x00000000
.size D_003996E4, . - D_003996E4

.align 3
dlabel D_STR_003996E8
/* 29A6E8 003996E8 */ .asciz "%d"
.align 2
/* 29A6EC 003996EC */ .asciz ""
.align 2
.size D_STR_003996E8, . - D_STR_003996E8

dlabel _BankChan1Req, local
/* 29A6F0 003996F0 00000000 */ .word 0x00000000
.size _BankChan1Req, . - _BankChan1Req

dlabel _BankChan1Stat, local
/* 29A6F4 003996F4 00000000 */ .word 0x00000000
.size _BankChan1Stat, . - _BankChan1Stat

/* Automatically generated and unreferenced pad */
dlabel D_003996F8
/* 29A6F8 003996F8 00000000 */ .word 0x00000000
/* 29A6FC 003996FC 00000000 */ .word 0x00000000
.size D_003996F8, . - D_003996F8

dlabel Scene_StageMap, global
/* 29A700 00399700 F8861800 */ .word Mdl_StageMapH
/* 29A704 00399704 C8951800 */ .word Cam_StageMap
.size Scene_StageMap, . - Scene_StageMap

dlabel Scene_StageMapA, global
/* 29A708 00399708 E88B1800 */ .word Mdl_StageMapA
/* 29A70C 0039970C C8951800 */ .word Cam_StageMap
.size Scene_StageMapA, . - Scene_StageMapA

dlabel Scene_StageMapY, global
/* 29A710 00399710 D8901800 */ .word Mdl_StageMapY
/* 29A714 00399714 C8951800 */ .word Cam_StageMap
.size Scene_StageMapY, . - Scene_StageMapY

dlabel Scene_CityHall, global
/* 29A718 00399718 48A51800 */ .word Mdl_CityHall
/* 29A71C 0039971C 78A61800 */ .word Cam_CityHall
.size Scene_CityHall, . - Scene_CityHall

dlabel Scene_OptCounter, global
/* 29A720 00399720 38AA1800 */ .word Mdl_OptCounter
/* 29A724 00399724 30AA1800 */ .word Cam_Notdef
.size Scene_OptCounter, . - Scene_OptCounter

dlabel Scene_RepCounter, global
/* 29A728 00399728 B0AA1800 */ .word Mdl_RepCounter
/* 29A72C 0039972C 30AA1800 */ .word Cam_Notdef
.size Scene_RepCounter, . - Scene_RepCounter

dlabel Scene_StgCounterLoad, global
/* 29A730 00399730 58AC1800 */ .word Mdl_StgCounterLoad
/* 29A734 00399734 30AA1800 */ .word Cam_Notdef
.size Scene_StgCounterLoad, . - Scene_StgCounterLoad

dlabel Scene_StgCounterSave, global
/* 29A738 00399738 00AE1800 */ .word Mdl_StgCounterSave
/* 29A73C 0039973C 30AA1800 */ .word Cam_Notdef
.size Scene_StgCounterSave, . - Scene_StgCounterSave

dlabel Scene_JimakuBak, global
/* 29A740 00399740 68B01800 */ .word Mdl_JimakuBak
/* 29A744 00399744 30AA1800 */ .word Cam_Notdef
.size Scene_JimakuBak, . - Scene_JimakuBak

dlabel UserName_InitialStr, local
/* 29A748 00399748 105F3900 */ .word RO_STR_00395F10
.size UserName_InitialStr, . - UserName_InitialStr

dlabel UserName_InitialStr2, local
/* 29A74C 0039974C 205F3900 */ .word RO_STR_00395F20
.size UserName_InitialStr2, . - UserName_InitialStr2

.align 3
/* Automatically generated and unreferenced pad */
dlabel D_STR_00399750
/* 29A750 00399750 */ .asciz "TEACHER"
.align 2
.size D_STR_00399750, . - D_STR_00399750

dlabel D_00399758
/* 29A758 00399758 00000000 */ .word 0x00000000
.size D_00399758, . - D_00399758

dlabel UserName_RankingNoSave, local
/* 29A75C 0039975C 58973900 */ .word D_00399758
.size UserName_RankingNoSave, . - UserName_RankingNoSave

.align 3
/* Automatically generated and unreferenced pad */
dlabel D_STR_00399760
/* 29A760 00399760 */ .asciz "DEC"
.align 2
/* 29A764 00399764 */ .asciz ""
.align 2
.size D_STR_00399760, . - D_STR_00399760

.align 3
dlabel D_STR_00399768
/* 29A768 00399768 */ .asciz "NOV"
.align 2
/* 29A76C 0039976C */ .asciz ""
.align 2
.size D_STR_00399768, . - D_STR_00399768

.align 3
dlabel D_STR_00399770
/* 29A770 00399770 */ .asciz "OCT"
.align 2
/* 29A774 00399774 */ .asciz ""
.align 2
.size D_STR_00399770, . - D_STR_00399770

.align 3
dlabel D_STR_00399778
/* 29A778 00399778 */ .asciz "SEP"
.align 2
/* 29A77C 0039977C */ .asciz ""
.align 2
.size D_STR_00399778, . - D_STR_00399778

.align 3
dlabel D_STR_00399780
/* 29A780 00399780 */ .asciz "AUG"
.align 2
/* 29A784 00399784 */ .asciz ""
.align 2
.size D_STR_00399780, . - D_STR_00399780

.align 3
dlabel D_STR_00399788
/* 29A788 00399788 */ .asciz "JLY"
.align 2
/* 29A78C 0039978C */ .asciz ""
.align 2
.size D_STR_00399788, . - D_STR_00399788

.align 3
dlabel D_STR_00399790
/* 29A790 00399790 */ .asciz "JUN"
.align 2
/* 29A794 00399794 */ .asciz ""
.align 2
.size D_STR_00399790, . - D_STR_00399790

.align 3
dlabel D_STR_00399798
/* 29A798 00399798 */ .asciz "MAY"
.align 2
/* 29A79C 0039979C */ .asciz ""
.align 2
.size D_STR_00399798, . - D_STR_00399798

.align 3
dlabel D_STR_003997A0
/* 29A7A0 003997A0 */ .asciz "APR"
.align 2
/* 29A7A4 003997A4 */ .asciz ""
.align 2
.size D_STR_003997A0, . - D_STR_003997A0

.align 3
dlabel D_STR_003997A8
/* 29A7A8 003997A8 */ .asciz "MAR"
.align 2
/* 29A7AC 003997AC */ .asciz ""
.align 2
.size D_STR_003997A8, . - D_STR_003997A8

.align 3
dlabel D_STR_003997B0
/* 29A7B0 003997B0 */ .asciz "FEB"
.align 2
/* 29A7B4 003997B4 */ .asciz ""
.align 2
.size D_STR_003997B0, . - D_STR_003997B0

.align 3
dlabel D_STR_003997B8
/* 29A7B8 003997B8 */ .asciz "JAN"
.align 2
.size D_STR_003997B8, . - D_STR_003997B8

dlabel tblTex, local
/* 29A7BC 003997BC 00000000 */ .word 0x00000000
.size tblTex, . - tblTex

dlabel UserList_Sw, local
/* 29A7C0 003997C0 00000000 */ .word 0x00000000
.size UserList_Sw, . - UserList_Sw

dlabel OptionList_Sw, local
/* 29A7C4 003997C4 00000000 */ .word 0x00000000
.size OptionList_Sw, . - OptionList_Sw

dlabel PopMenu_Sw, local
/* 29A7C8 003997C8 00000000 */ .word 0x00000000
.size PopMenu_Sw, . - PopMenu_Sw

dlabel SaveMenu_Sw, local
/* 29A7CC 003997CC 00000000 */ .word 0x00000000
.size SaveMenu_Sw, . - SaveMenu_Sw

dlabel JukeMenu_Sw, local
/* 29A7D0 003997D0 00000000 */ .word 0x00000000
.size JukeMenu_Sw, . - JukeMenu_Sw

dlabel nTim.174, local
/* 29A7D4 003997D4 00000000 */ .word 0x00000000
.size nTim.174, . - nTim.174

dlabel map0Msk.178, local
/* 29A7D8 003997D8 */ .byte 0x01
/* 29A7D9 003997D9 */ .byte 0x00
/* 29A7DA 003997DA */ .byte 0x00
/* 29A7DB 003997DB */ .byte 0x00
/* 29A7DC 003997DC */ .byte 0x01
/* 29A7DD 003997DD */ .byte 0x01
/* 29A7DE 003997DE */ .byte 0x01
/* 29A7DF 003997DF */ .byte 0x01
.size map0Msk.178, . - map0Msk.178

dlabel isRun.315, local
/* 29A7E0 003997E0 FEFFFFFF */ .word 0xFFFFFFFE
.size isRun.315, . - isRun.315

/* Automatically generated and unreferenced pad */
dlabel D_003997E4
/* 29A7E4 003997E4 00000000 */ .word 0x00000000
.size D_003997E4, . - D_003997E4

.align 3
dlabel D_STR_003997E8
/* 29A7E8 003997E8 */ .asciz "%d"
.align 2
/* 29A7EC 003997EC */ .asciz ""
.align 2
.size D_STR_003997E8, . - D_STR_003997E8

.align 3
dlabel D_STR_003997F0
/* 29A7F0 003997F0 */ .asciz "%s"
.align 2
/* 29A7F4 003997F4 */ .asciz ""
.align 2
.size D_STR_003997F0, . - D_STR_003997F0

.align 3
dlabel D_STR_003997F8
/* 29A7F8 003997F8 */ .asciz "STAGE%d"
.align 2
.size D_STR_003997F8, . - D_STR_003997F8

dlabel D_00399800
/* 29A800 00399800 20535441 */ .word 0x41545320
/* 29A804 00399804 47453F00 */ .word usrMemoryData + 0x191C7
.size D_00399800, . - D_00399800

.align 3
dlabel D_STR_00399808
/* 29A808 00399808 */ .asciz "--:--"
.align 2
.size D_STR_00399808, . - D_STR_00399808

.align 3
dlabel D_STR_00399810
/* 29A810 00399810 */ .asciz "%02d"
.align 2
.size D_STR_00399810, . - D_STR_00399810

.align 3
dlabel D_STR_00399818
/* 29A818 00399818 */ .asciz "%06d"
.align 2
.size D_STR_00399818, . - D_STR_00399818

dlabel _TexFunc, local
/* 29A820 00399820 00000000 */ .word 0x00000000
.size _TexFunc, . - _TexFunc

dlabel HOSIObj, local
/* 29A824 00399824 00000000 */ .word 0x00000000
.size HOSIObj, . - HOSIObj

dlabel MapTime, global
/* 29A828 00399828 00000000 */ .word 0x00000000
/* 29A82C 0039982C 00000000 */ .word 0x00000000
.size MapTime, . - MapTime

dlabel HedderID, local
/* 29A830 00399830 80613900 */ .word RO_STR_00396180
.size HedderID, . - HedderID

dlabel FooterID, local
/* 29A834 00399834 90613900 */ .word RO_STR_00396190
.size FooterID, . - FooterID

dlabel pUChkWork, local
/* 29A838 00399838 00000000 */ .word 0x00000000
.size pUChkWork, . - pUChkWork

/* Automatically generated and unreferenced pad */
dlabel D_0039983C
/* 29A83C 0039983C 00000000 */ .word 0x00000000
.size D_0039983C, . - D_0039983C

dlabel D_00399840
/* 29A840 00399840 */ .byte 0x4C
/* 29A841 00399841 */ .byte 0x4F
/* 29A842 00399842 */ .byte 0x47
/* 29A843 00399843 */ .byte 0x3F
/* 29A844 00399844 */ .byte 0x3F
/* 29A845 00399845 */ .byte 0x3F
/* 29A846 00399846 */ .byte 0x00
/* 29A847 00399847 */ .byte 0x00
.size D_00399840, . - D_00399840

.align 3
dlabel D_STR_00399848
/* 29A848 00399848 */ .asciz "LOG%03d"
.align 2
.size D_STR_00399848, . - D_STR_00399848

dlabel D_00399850
/* 29A850 00399850 */ .byte 0x52
/* 29A851 00399851 */ .byte 0x45
/* 29A852 00399852 */ .byte 0x50
/* 29A853 00399853 */ .byte 0x3F
/* 29A854 00399854 */ .byte 0x3F
/* 29A855 00399855 */ .byte 0x3F
/* 29A856 00399856 */ .byte 0x00
/* 29A857 00399857 */ .byte 0x00
.size D_00399850, . - D_00399850

.align 3
dlabel D_STR_00399858
/* 29A858 00399858 */ .asciz "REP%03d"
.align 2
.size D_STR_00399858, . - D_STR_00399858

dlabel D_00399860
/* 29A860 00399860 */ .byte 0x3F
/* 29A861 00399861 */ .byte 0x3F
/* 29A862 00399862 */ .byte 0x3F
/* 29A863 00399863 */ .byte 0x3F
/* 29A864 00399864 */ .byte 0x3F
/* 29A865 00399865 */ .byte 0x3F
/* 29A866 00399866 */ .byte 0x00
/* 29A867 00399867 */ .byte 0x00
.size D_00399860, . - D_00399860

.align 3
dlabel D_STR_00399868
/* 29A868 00399868 */ .asciz "LOG"
.align 2
/* 29A86C 0039986C */ .asciz ""
.align 2
.size D_STR_00399868, . - D_STR_00399868

.align 3
dlabel D_STR_00399870
/* 29A870 00399870 */ .asciz "REP"
.align 2
/* 29A874 00399874 */ .asciz ""
.align 2
.size D_STR_00399870, . - D_STR_00399870

.align 3
dlabel D_STR_00399878
/* 29A878 00399878 */ .asciz "/"
.align 2
/* 29A87C 0039987C */ .asciz ""
.align 2
.size D_STR_00399878, . - D_STR_00399878

dlabel D_00399880
/* 29A880 00399880 */ .byte 0x2F
/* 29A881 00399881 */ .byte 0x2A
/* 29A882 00399882 */ .byte 0x00
/* 29A883 00399883 */ .byte 0x00
/* 29A884 00399884 */ .byte 0x00
/* 29A885 00399885 */ .byte 0x00
/* 29A886 00399886 */ .byte 0x00
/* 29A887 00399887 */ .byte 0x00
.size D_00399880, . - D_00399880

.align 3
dlabel D_STR_00399888
/* 29A888 00399888 */ .asciz "SAVE"
.align 2
.size D_STR_00399888, . - D_STR_00399888

dlabel _PadFont_SW, local
/* 29A890 00399890 00000000 */ .word 0x00000000
.size _PadFont_SW, . - _PadFont_SW

dlabel _PadArrowState, local
/* 29A894 00399894 00000000 */ .word 0x00000000
.size _PadArrowState, . - _PadArrowState

/* Automatically generated and unreferenced pad */
dlabel D_00399898
/* 29A898 00399898 00000000 */ .word 0x00000000
/* 29A89C 0039989C 00000000 */ .word 0x00000000
.size D_00399898, . - D_00399898

dlabel _PkDefSCISSOR, local
/* 29A8A0 003998A0 00007F02 */ .word 0x027F0000
/* 29A8A4 003998A4 0000DF00 */ .word usrMemoryData + 0xA14C80
.size _PkDefSCISSOR, . - _PkDefSCISSOR

/* Automatically generated and unreferenced pad */
dlabel D_003998A8
/* 29A8A8 003998A8 00000000 */ .word 0x00000000
/* 29A8AC 003998AC 00000000 */ .word 0x00000000
.size D_003998A8, . - D_003998A8

dlabel _PkDefZBUFFER, local
/* 29A8B0 003998B0 00000000 */ .word 0x00000000
/* 29A8B4 003998B4 00000000 */ .word 0x00000000
.size _PkDefZBUFFER, . - _PkDefZBUFFER

dlabel gifRegisterModeInitialized, local
/* 29A8B8 003998B8 00000000 */ .word 0x00000000
.size gifRegisterModeInitialized, . - gifRegisterModeInitialized

dlabel prSpramData, local
/* 29A8BC 003998BC 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel workAreaTopAddress, local
/* 29A8C0 003998C0 00000000 */ .word 0x00000000
.size workAreaTopAddress, . - workAreaTopAddress

dlabel databaseInitialized, local
/* 29A8C4 003998C4 00000000 */ .word 0x00000000
.size databaseInitialized, . - databaseInitialized

dlabel warned.1791, local
/* 29A8C8 003998C8 00000000 */ .word 0x00000000
.size warned.1791, . - warned.1791

dlabel prFrameRate, global
/* 29A8CC 003998CC 0000803F */ .float 1
.size prFrameRate, . - prFrameRate

dlabel prInverseFrameRate, global
/* 29A8D0 003998D0 0000803F */ .float 1
.size prInverseFrameRate, . - prInverseFrameRate

dlabel _$tmp_0.2266, local
/* 29A8D4 003998D4 00000000 */ .word 0x00000000
.size _$tmp_0.2266, . - _$tmp_0.2266

dlabel _$tmp_1.2271, local
/* 29A8D8 003998D8 00000000 */ .word 0x00000000
.size _$tmp_1.2271, . - _$tmp_1.2271

dlabel prCurrentStage, global
/* 29A8DC 003998DC 00000000 */ .word 0x00000000
.size prCurrentStage, . - prCurrentStage

dlabel prSpramData, local
/* 29A8E0 003998E0 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel D_FLT_003998E4
/* 29A8E4 003998E4 FFFF7F7F */ .float 3.402823466e+38
.size D_FLT_003998E4, . - D_FLT_003998E4

dlabel D_FLT_003998E8
/* 29A8E8 003998E8 FFFF7F7F */ .float 3.402823466e+38
.size D_FLT_003998E8, . - D_FLT_003998E8

dlabel prSpramData, local
/* 29A8EC 003998EC 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel prSpramData, local
/* 29A8F0 003998F0 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel prSpramData, local
/* 29A8F4 003998F4 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel mfifoProcessing, local
/* 29A8F8 003998F8 00000000 */ .word 0x00000000
.size mfifoProcessing, . - mfifoProcessing

dlabel _$tmp_0.1744, local
/* 29A8FC 003998FC 00000000 */ .word 0x00000000
.size _$tmp_0.1744, . - _$tmp_0.1744

dlabel _$tmp_1.1749, local
/* 29A900 00399900 00000000 */ .word 0x00000000
.size _$tmp_1.1749, . - _$tmp_1.1749

dlabel _$tmp_2.1751, local
/* 29A904 00399904 00000000 */ .word 0x00000000
.size _$tmp_2.1751, . - _$tmp_2.1751

dlabel _$tmp_3.1756, local
/* 29A908 00399908 00000000 */ .word 0x00000000
.size _$tmp_3.1756, . - _$tmp_3.1756

dlabel _$tmp_4.1794, local
/* 29A90C 0039990C 00000000 */ .word 0x00000000
.size _$tmp_4.1794, . - _$tmp_4.1794

dlabel _$tmp_5.1840, local
/* 29A910 00399910 00000000 */ .word 0x00000000
.size _$tmp_5.1840, . - _$tmp_5.1840

dlabel _$tmp_6.1857, local
/* 29A914 00399914 00000000 */ .word 0x00000000
.size _$tmp_6.1857, . - _$tmp_6.1857

dlabel D_FLT_00399918
/* 29A918 00399918 FFFF7F7F */ .float 3.402823466e+38
.size D_FLT_00399918, . - D_FLT_00399918

dlabel D_FLT_0039991C
/* 29A91C 0039991C FFFF7FFF */ .float -3.402823466e+38
.size D_FLT_0039991C, . - D_FLT_0039991C

dlabel prSpramData, local
/* 29A920 00399920 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel D_FLT_00399924
/* 29A924 00399924 FFFF7F7F */ .float 3.402823466e+38
.size D_FLT_00399924, . - D_FLT_00399924

dlabel prSpramData, local
/* 29A928 00399928 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel D_FLT_0039992C
/* 29A92C 0039992C FFFF7F7F */ .float 3.402823466e+38
.size D_FLT_0039992C, . - D_FLT_0039992C

dlabel prSpramData, local
/* 29A930 00399930 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel _$tmp_0.1705, local
/* 29A934 00399934 00000000 */ .word 0x00000000
.size _$tmp_0.1705, . - _$tmp_0.1705

dlabel prSpramData, local
/* 29A938 00399938 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel spriteDefinitionZ, local
/* 29A93C 0039993C 00000000 */ .word 0x00000000
.size spriteDefinitionZ, . - spriteDefinitionZ

dlabel randomSeed, local
/* 29A940 00399940 01000000 */ .word 0x00000001
.size randomSeed, . - randomSeed

dlabel poolIndex.1140, local
/* 29A944 00399944 00000000 */ .word 0x00000000
.size poolIndex.1140, . - poolIndex.1140

dlabel prSpramData, local
/* 29A948 00399948 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel prMendererRatio, global
/* 29A94C 0039994C 00000000 */ .float 0
.size prMendererRatio, . - prMendererRatio

dlabel prMendererSyncRatio, global
/* 29A950 00399950 00000000 */ .float 0
.size prMendererSyncRatio, . - prMendererSyncRatio

dlabel prMendererGettingWorse, global
/* 29A954 00399954 01000000 */ .word 0x00000001
.size prMendererGettingWorse, . - prMendererGettingWorse

dlabel prMendererColorModulation, global
/* 29A958 00399958 01000000 */ .word 0x00000001
.size prMendererColorModulation, . - prMendererColorModulation

dlabel prMendererSpeed, global
/* 29A95C 0039995C 0000803F */ .float 1
.size prMendererSpeed, . - prMendererSpeed

dlabel prMendererFade, global
/* 29A960 00399960 0000803F */ .float 1
.size prMendererFade, . - prMendererFade

dlabel prMendererDistance, global
/* 29A964 00399964 00000000 */ .float 0
.size prMendererDistance, . - prMendererDistance

dlabel prMendererWidth, global
/* 29A968 00399968 0000803F */ .float 1
.size prMendererWidth, . - prMendererWidth

dlabel prMendererLength, global
/* 29A96C 0039996C 0000803F */ .float 1
.size prMendererLength, . - prMendererLength

dlabel prSchoolLeaderIndex, global
/* 29A970 00399970 00000000 */ .float 0
.size prSchoolLeaderIndex, . - prSchoolLeaderIndex

dlabel mendererInitialized, local
/* 29A974 00399974 00000000 */ .word 0x00000000
.size mendererInitialized, . - mendererInitialized

dlabel randomSeed, local
/* 29A978 00399978 00000000 */ .word 0x00000000
.size randomSeed, . - randomSeed

dlabel modulationHue, local
/* 29A97C 0039997C 00000000 */ .float 0
.size modulationHue, . - modulationHue

dlabel modulationAwfulBlight, local
/* 29A980 00399980 00000000 */ .float 0
.size modulationAwfulBlight, . - modulationAwfulBlight

dlabel noodleRotation, local
/* 29A984 00399984 00000000 */ .word 0x00000000
.size noodleRotation, . - noodleRotation

dlabel deceleratingMenderer, global
/* 29A988 00399988 00000000 */ .word 0x00000000
.size deceleratingMenderer, . - deceleratingMenderer

dlabel decelerateRatio, global
/* 29A98C 0039998C 0000803F */ .float 1
.size decelerateRatio, . - decelerateRatio

dlabel lastRatio.1781, local
/* 29A990 00399990 00000000 */ .float 0
.size lastRatio.1781, . - lastRatio.1781

dlabel prMendererTbp, global
/* 29A994 00399994 00000000 */ .word 0x00000000
.size prMendererTbp, . - prMendererTbp

dlabel prMendererWorkFbp, global
/* 29A998 00399998 00000000 */ .word 0x00000000
.size prMendererWorkFbp, . - prMendererWorkFbp

dlabel prMendererDrawFbp, global
/* 29A99C 0039999C 00000000 */ .word 0x00000000
.size prMendererDrawFbp, . - prMendererDrawFbp

dlabel mendererInitialized, local
/* 29A9A0 003999A0 00000000 */ .word 0x00000000
.size mendererInitialized, . - mendererInitialized

dlabel mendererCreating, local
/* 29A9A4 003999A4 00000000 */ .word 0x00000000
.size mendererCreating, . - mendererCreating

dlabel sync_stage.1173, local
/* 29A9A8 003999A8 00000000 */ .float 0
.size sync_stage.1173, . - sync_stage.1173

dlabel awfulRotationAngle, local
/* 29A9AC 003999AC 00000000 */ .float 0
.size awfulRotationAngle, . - awfulRotationAngle

dlabel prSpramData, local
/* 29A9B0 003999B0 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel warned.1161, local
/* 29A9B4 003999B4 00000000 */ .word 0x00000000
.size warned.1161, . - warned.1161

dlabel mmsize.1146, local
/* 29A9B8 003999B8 */ .byte 0x30
/* 29A9B9 003999B9 */ .byte 0x30
/* 29A9BA 003999BA */ .byte 0x50
/* 29A9BB 003999BB */ .byte 0x50
/* 29A9BC 003999BC */ .byte 0x50
/* 29A9BD 003999BD */ .byte 0x60
/* 29A9BE 003999BE */ .byte 0x60
/* 29A9BF 003999BF */ .byte 0x60
.size mmsize.1146, . - mmsize.1146

dlabel _$tmp_0.2029, local
/* 29A9C0 003999C0 00000000 */ .word 0x00000000
.size _$tmp_0.2029, . - _$tmp_0.2029

dlabel prSpramData, local
/* 29A9C4 003999C4 00000070 */ .word 0x70000000
.size prSpramData, . - prSpramData

dlabel D_FLT_003999C8
/* 29A9C8 003999C8 FFFF7F7F */ .float 3.402823466e+38
/* 29A9CC 003999CC 00000000 */ .float 0
.size D_FLT_003999C8, . - D_FLT_003999C8

dlabel _t8NaVECTOR2Zfi2$ZERO, global
/* 29A9D0 003999D0 00000000 */ .float 0
/* 29A9D4 003999D4 00000000 */ .float 0
.size _t8NaVECTOR2Zfi2$ZERO, . - _t8NaVECTOR2Zfi2$ZERO
